### ISSUE TITLE
Use Laravel Framework Controller than App\Http\Controller

### ISSUE THREAD

**Issue by shirshak55** [chris-ware/nova-clock-card#1]
I think AreRoutesCached class should extend Illuminate\Routing\Controller; than App\Http\Controller . 

It is due to fact many people don't use App\Http\Controller or move that file to another location

**Comment by flxsource** [comment]
@shirshak55 Nothing in this package extends any controllers. Could you provide more detail please?

**Comment by shirshak55** [comment]
@fixsource Sorry bro was on wrong that it was that route cache card plugin .

Again extremly sorry for my mistake sir
